# Dockerfile para el servicio de MySQL
FROM mysql:5.7

# Variables de entorno para configurar la base de datos
ENV MYSQL_DATABASE=wordpress \
    MYSQL_USER=root \
    MYSQL_PASSWORD=example \
    MYSQL_ROOT_PASSWORD=example
